name: Build Gradle project and upload jar to private server
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  upload:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Build with gradle
        run: ./gradlew build
      - name: Create new release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./build/libs/*.jar"
          generateReleaseNotes: true
      - name: Upload jar via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/*.jar"
          target: "/var/sftp/uploads/util_lib_build/"
