name: Build and publish Gradle project
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.1.0
      - name: Build with gradle
        run: ./gradlew build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build
          if-no-files-found: error

  deploy:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - name: Create new release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./build/libs/*.jar"
          generateReleaseNotes: true
      - name: Prepare files to move to the server
        run: |
          git_tag=$(git describe --tags --always --first-parent)
          mkdir ./scp_build/"$git_tag"
          mv ./build/libs/*.jar ./scp_build/"{$git_tag}"
      - name: Upload jar via scp
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "./scp_build/**/*.jar"
          target: "/var/sftp/uploads/util_lib_build/"
          strip_components: 1
      - name: Deploy docs to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: ./build/docs/javadoc
          branch: docs